<template>
	<div>
		Lincoln Building 2
		1921/1922
		In 1921/1922 with more Whites living in the Northend and Black population moving to Crawfordsville’s East End, the original Lincoln School at the corner of Spring and Walnut Streets was abandoned, renovated, and became Horace Mann School. A new Lincoln School was built on East Wabash Avenue to accommodate Black students grades one through eight. Unfortunately, the construction was not quite finished in time for school year to begin, so a temporary building made from tin was erected. It was referred to as the Tin School which stood near the bridge on Wabash Avenue. It originally had four rooms but walls were removed to make two rooms. Students and teachers came and went, and segregation status quo continued.
		The second Lincoln School building was not much different than the first. Francis Wooden remembered “there was a basement in a main floor, two rooms on each side of the hall. They didn’t have kindergarten. In fact, kindergarten was something new later on. You went to different rooms as you moved from grade to grade. At that time, you did what your teachers told you or they’d make you stand in the corner give you a spanking, whatever they thought best. Students were taught reading, writing and arithmetic. Teachers would start students of one grade level on one subject, and then move to another part of the room to start another grade on their lessons.
		Elsie Bard remembers that she was raised in the north part of town and caught the school bus to come to the east side for Lincoln School. She was there through sixth grade. She recalled, “It had two rooms. There was the first, second, and third grade in one room; the fourth, fifth, and sixth were in the other room. The building had no windows in the front and very large windows in the back. It had a girls’ playroom and the boys’ play room downstairs. There were restrooms, and a large playground. I remember doing quite a few plays and a lot of singing. I remember the teachers had quite a few children to really be teaching and couldn’t devote their full time to them, but that’s what they had to work with, so they did the best they could.
		Maxine Burdette also had clear memories of her time at Lincoln School. “If you were smart enough to get by, to make it through the seventh grade, you were all right. But we had struggle to do this. In her earlier years, Miss Clara Freeze and Maudeline Bailey really taught us. They were really good teachers and taught us well in our elementary years. I had an art teacher who was White who would come to the school to give a special art classes. We also had a music teacher that would come to the school- her name was Mrs. Porter. We thought it was real funny as she would have a little pitch pipe and she would tune us in. But most of the kids in those grades seem to have a happy life at that school because that’s all we knew there. We had a playground we went out and played. We had to make up our own games. Lincoln School was all right at that time. After I got to the junior high school I saw a whole lot that I had missed by not having the right supervision, not having teaching I should have had.”
		1932-3
		According to the Crawfordsville School Board minutes dated 6 December 1932, Lincoln School was closed 20 January 1933 in the midst of the Depression and desegregation became the adopted policy of Crawfordsville Schools. Black students transferred to other local schools or to those school districts in which they lived. The rationale for the closure centered on cost; the per capita cost of the Lincoln School ran 50% higher than the average costs. Thus began an integration experiment which once began, met with opposition and eventually failed.
		Vicki Hudson Swisher’s mother attended Lincoln school during the Depression when both Lincoln and St. Bernard’s closed because of expense. Her mother then attended Wilson and was the class whipping boy meaning when someone needed to be disciplined she took the punishment instead. The teacher did not want her in class. After backlash, criticism, intimidations, threats, and fears of revolt, Lincoln School reopened for the 1936-7 school year. Lincoln school was closed forever at the end of the 1946 1947 school year.
		The demise of the school is murky at best. According to Black residents, allegedly a Black lady owned the Lincoln property and she left it to the Black citizenry. But the city intervened and ordered the demolition. The company that tore the building down said it was the hardest building they’d ever had to knock down. Originally, the city had planned to remodel it and put a ramp in for the senior citizens. Instead, the building became a recreation center
		Lincoln School Building 2 as a Recreation Center
		Lincoln School for Colored Children was eventually deemed unnecessary by the 1960s when separate but equal legislation was deemed illegal. This second building became the Lincoln Center, a recreation center for the Black community, a meeting place for the Baptist Church, Black judges and the Colored Prince Hall Masonic Lodge that was very active with members from Lebanon and Greencastle. According to Gail Pebworth, sometime in the late 1960s or early 70s a group of younger faculty from Wabash, probably led by Eldon Parks, got together to crudely rehab the building. People would serve popcorn and show movies for neighborhood kids when they could not attend movies downtown or had segregated seating. The building was demolished in 1981 and now only green space and basketball courts remain.
	</div>
</template>
<script></script>
<style></style>
